#!/bin/sh


_bc() {
	bspc config "$@"
}

_check() {
	command -v "$1" > /dev/null
}


_check xorg_automonitor && xorg_automonitor

_check bspwm_conf_desktops && bspwm_conf_desktops


_bc automatic_scheme spiral
_bc initial_polarity second_child
_bc split_ratio 0.5
_bc border_width 2
_bc window_gap 0
_bc single_monocle true
_bc borderless_monocle false 
_bc gapless_monocle true
_bc focus_follows_pointer true
_bc pointer_follows_monitor true
_bc pointer_modifier mod4
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc ignore_ewmh_focus false

_check bspwm_conf_colors && bspwm_conf_colors

_check bspwm_external_rules && \
    _bc external_rules_command \
	"$(command -v bspwm_external_rules)"


_check setxkbmap && setxkbmap -option caps:escape

_check sxhkd && sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

_check xrdb && xrdb -merge "$HOME"/.config/x11/xresources &

_check xsetroot && xsetroot -cursor_name left_ptr &

_check xsettingsd && xsettingsd -c "$HOME"/.config/xsettingsd/xsettingsd.conf &

_check dunst && dunst & 

wmname "LG3D"
