[line_break]
disabled = true 

[character]
success_symbol="[❯❯❯](bold green)"
error_symbol="[❯❯❯](bold red)"

[directory]
format="$path "

# [python]
# pyenv_version_name = true
# python_binary = "python3"



